In [4]:
from pandas import read_csv
import numpy as np
import pandas as pd
#READING THE DATA
dataset = read_csv('pima-indians-diabetes.data.csv', header=None)
print(dataset.describe())

                0           1           2           3           4           5  \
count  768.000000  768.000000  768.000000  768.000000  768.000000  768.000000
mean     3.845052  120.894531   69.105469   20.536458   79.799479   31.992578
std      3.369578   31.972618   19.355807   15.952218  115.244002    7.884160
min      0.000000    0.000000    0.000000    0.000000    0.000000    0.000000
25%      1.000000   99.000000   62.000000    0.000000    0.000000   27.300000
50%      3.000000  117.000000   72.000000   23.000000   30.500000   32.000000
75%      6.000000  140.250000   80.000000   32.000000  127.250000   36.600000
max     17.000000  199.000000  122.000000   99.000000  846.000000   67.100000

                6           7           8
count  768.000000  768.000000  768.000000
mean     0.471876   33.240885    0.348958
std      0.331329   11.760232    0.476951
min      0.078000   21.000000    0.000000
25%      0.243750   24.000000    0.000000
50%      0.372500   29.000000    0.000000
75%      0.626250   41.000000    1.000000
max      2.420000   81.000000    1.000000

In [5]:
#Printing the first 20 rows of the dataset
print(dataset.head(20))
#Similarly tail is used to print the rows from the last.

     0    1   2   3    4     5      6   7  8
0    6  148  72  35    0  33.6  0.627  50  1
1    1   85  66  29    0  26.6  0.351  31  0
2    8  183  64   0    0  23.3  0.672  32  1
3    1   89  66  23   94  28.1  0.167  21  0
4    0  137  40  35  168  43.1  2.288  33  1
5    5  116  74   0    0  25.6  0.201  30  0
6    3   78  50  32   88  31.0  0.248  26  1
7   10  115   0   0    0  35.3  0.134  29  0
8    2  197  70  45  543  30.5  0.158  53  1
9    8  125  96   0    0   0.0  0.232  54  1
10   4  110  92   0    0  37.6  0.191  30  0
11  10  168  74   0    0  38.0  0.537  34  1
12  10  139  80   0    0  27.1  1.441  57  0
13   1  189  60  23  846  30.1  0.398  59  1
14   5  166  72  19  175  25.8  0.587  51  1
15   7  100   0   0    0  30.0  0.484  32  1
16   0  118  84  47  230  45.8  0.551  31  1
17   7  107  74   0    0  29.6  0.254  31  1
18   1  103  30  38   83  43.3  0.183  33  0
19   1  115  70  30   96  34.6  0.529  32  1

In [6]:
#Printing the number of zeroes in the respective columns
print((dataset[[1,2,3,4,5]] == 0).sum())

1      5
2     35
3    227
4    374
5     11
dtype: int64

In [7]:
#printing the number of null values in a dataset
print(dataset.isnull().sum())

0    0
1    0
2    0
3    0
4    0
5    0
6    0
7    0
8    0
dtype: int64

In [8]:
#Replacing the zeroes with Nan values in numpy
#Nan stands for not a number
dataset[[1,2,3,4,5]] = dataset[[1,2,3,4,5]].replace(0, np.NaN)
dataset

      0      1     2     3      4     5      6   7  8
0     6  148.0  72.0  35.0    NaN  33.6  0.627  50  1
1     1   85.0  66.0  29.0    NaN  26.6  0.351  31  0
2     8  183.0  64.0   NaN    NaN  23.3  0.672  32  1
3     1   89.0  66.0  23.0   94.0  28.1  0.167  21  0
4     0  137.0  40.0  35.0  168.0  43.1  2.288  33  1
5     5  116.0  74.0   NaN    NaN  25.6  0.201  30  0
6     3   78.0  50.0  32.0   88.0  31.0  0.248  26  1
7    10  115.0   NaN   NaN    NaN  35.3  0.134  29  0
8     2  197.0  70.0  45.0  543.0  30.5  0.158  53  1
9     8  125.0  96.0   NaN    NaN   NaN  0.232  54  1
10    4  110.0  92.0   NaN    NaN  37.6  0.191  30  0
11   10  168.0  74.0   NaN    NaN  38.0  0.537  34  1
12   10  139.0  80.0   NaN    NaN  27.1  1.441  57  0
13    1  189.0  60.0  23.0  846.0  30.1  0.398  59  1
14    5  166.0  72.0  19.0  175.0  25.8  0.587  51  1
15    7  100.0   NaN   NaN    NaN  30.0  0.484  32  1
16    0  118.0  84.0  47.0  230.0  45.8  0.551  31  1
17    7  107.0  74.0   NaN    NaN  29.6  0.254  31  1
18    1  103.0  30.0  38.0   83.0  43.3  0.183  33  0
19    1  115.0  70.0  30.0   96.0  34.6  0.529  32  1
20    3  126.0  88.0  41.0  235.0  39.3  0.704  27  0
21    8   99.0  84.0   NaN    NaN  35.4  0.388  50  0
22    7  196.0  90.0   NaN    NaN  39.8  0.451  41  1
23    9  119.0  80.0  35.0    NaN  29.0  0.263  29  1
24   11  143.0  94.0  33.0  146.0  36.6  0.254  51  1
25   10  125.0  70.0  26.0  115.0  31.1  0.205  41  1
26    7  147.0  76.0   NaN    NaN  39.4  0.257  43  1
27    1   97.0  66.0  15.0  140.0  23.2  0.487  22  0
28   13  145.0  82.0  19.0  110.0  22.2  0.245  57  0
29    5  117.0  92.0   NaN    NaN  34.1  0.337  38  0
..   ..    ...   ...   ...    ...   ...    ...  .. ..
738   2   99.0  60.0  17.0  160.0  36.6  0.453  21  0
739   1  102.0  74.0   NaN    NaN  39.5  0.293  42  1
740  11  120.0  80.0  37.0  150.0  42.3  0.785  48  1
741   3  102.0  44.0  20.0   94.0  30.8  0.400  26  0
742   1  109.0  58.0  18.0  116.0  28.5  0.219  22  0
743   9  140.0  94.0   NaN    NaN  32.7  0.734  45  1
744  13  153.0  88.0  37.0  140.0  40.6  1.174  39  0
745  12  100.0  84.0  33.0  105.0  30.0  0.488  46  0
746   1  147.0  94.0  41.0    NaN  49.3  0.358  27  1
747   1   81.0  74.0  41.0   57.0  46.3  1.096  32  0
748   3  187.0  70.0  22.0  200.0  36.4  0.408  36  1
749   6  162.0  62.0   NaN    NaN  24.3  0.178  50  1
750   4  136.0  70.0   NaN    NaN  31.2  1.182  22  1
751   1  121.0  78.0  39.0   74.0  39.0  0.261  28  0
752   3  108.0  62.0  24.0    NaN  26.0  0.223  25  0
753   0  181.0  88.0  44.0  510.0  43.3  0.222  26  1
754   8  154.0  78.0  32.0    NaN  32.4  0.443  45  1
755   1  128.0  88.0  39.0  110.0  36.5  1.057  37  1
756   7  137.0  90.0  41.0    NaN  32.0  0.391  39  0
757   0  123.0  72.0   NaN    NaN  36.3  0.258  52  1
758   1  106.0  76.0   NaN    NaN  37.5  0.197  26  0
759   6  190.0  92.0   NaN    NaN  35.5  0.278  66  1
760   2   88.0  58.0  26.0   16.0  28.4  0.766  22  0
761   9  170.0  74.0  31.0    NaN  44.0  0.403  43  1
762   9   89.0  62.0   NaN    NaN  22.5  0.142  33  0
763  10  101.0  76.0  48.0  180.0  32.9  0.171  63  0
764   2  122.0  70.0  27.0    NaN  36.8  0.340  27  0
765   5  121.0  72.0  23.0  112.0  26.2  0.245  30  0
766   1  126.0  60.0   NaN    NaN  30.1  0.349  47  1
767   1   93.0  70.0  31.0    NaN  30.4  0.315  23  0

[768 rows x 9 columns]

In [10]:
#Gives the count of total number of rows having missing values 
print(sum([True for idx,row in dataset.iterrows() if any(row.isnull())]))

#Gives the count of total number of cells having missing values
sum(dataset.isnull().values.ravel())

376

652

In [13]:
#printing the number of null values in a dataset
print(dataset.isnull().sum())

dataset.isnull().sum().sum()

0      0
1      5
2     35
3    227
4    374
5     11
6      0
7      0
8      0
dtype: int64

652

In [15]:
#removing missing values rows
dataset.dropna(inplace=True)

dataset

      0      1      2     3      4     5      6   7  8
3     1   89.0   66.0  23.0   94.0  28.1  0.167  21  0
4     0  137.0   40.0  35.0  168.0  43.1  2.288  33  1
6     3   78.0   50.0  32.0   88.0  31.0  0.248  26  1
8     2  197.0   70.0  45.0  543.0  30.5  0.158  53  1
13    1  189.0   60.0  23.0  846.0  30.1  0.398  59  1
14    5  166.0   72.0  19.0  175.0  25.8  0.587  51  1
16    0  118.0   84.0  47.0  230.0  45.8  0.551  31  1
18    1  103.0   30.0  38.0   83.0  43.3  0.183  33  0
19    1  115.0   70.0  30.0   96.0  34.6  0.529  32  1
20    3  126.0   88.0  41.0  235.0  39.3  0.704  27  0
24   11  143.0   94.0  33.0  146.0  36.6  0.254  51  1
25   10  125.0   70.0  26.0  115.0  31.1  0.205  41  1
27    1   97.0   66.0  15.0  140.0  23.2  0.487  22  0
28   13  145.0   82.0  19.0  110.0  22.2  0.245  57  0
31    3  158.0   76.0  36.0  245.0  31.6  0.851  28  1
32    3   88.0   58.0  11.0   54.0  24.8  0.267  22  0
35    4  103.0   60.0  33.0  192.0  24.0  0.966  33  0
39    4  111.0   72.0  47.0  207.0  37.1  1.390  56  1
40    3  180.0   64.0  25.0   70.0  34.0  0.271  26  0
43    9  171.0  110.0  24.0  240.0  45.4  0.721  54  1
50    1  103.0   80.0  11.0   82.0  19.4  0.491  22  0
51    1  101.0   50.0  15.0   36.0  24.2  0.526  26  0
52    5   88.0   66.0  21.0   23.0  24.4  0.342  30  0
53    8  176.0   90.0  34.0  300.0  33.7  0.467  58  1
54    7  150.0   66.0  42.0  342.0  34.7  0.718  42  0
56    7  187.0   68.0  39.0  304.0  37.7  0.254  41  1
57    0  100.0   88.0  60.0  110.0  46.8  0.962  31  0
59    0  105.0   64.0  41.0  142.0  41.5  0.173  22  0
63    2  141.0   58.0  34.0  128.0  25.4  0.699  24  0
68    1   95.0   66.0  13.0   38.0  19.6  0.334  25  0
..   ..    ...    ...   ...    ...   ...    ...  .. ..
707   2  127.0   46.0  21.0  335.0  34.4  0.176  22  0
709   2   93.0   64.0  32.0  160.0  38.0  0.674  23  1
710   3  158.0   64.0  13.0  387.0  31.2  0.295  24  0
711   5  126.0   78.0  27.0   22.0  29.6  0.439  40  0
713   0  134.0   58.0  20.0  291.0  26.4  0.352  21  0
715   7  187.0   50.0  33.0  392.0  33.9  0.826  34  1
716   3  173.0   78.0  39.0  185.0  33.8  0.970  31  1
718   1  108.0   60.0  46.0  178.0  35.5  0.415  24  0
721   1  114.0   66.0  36.0  200.0  38.1  0.289  21  0
722   1  149.0   68.0  29.0  127.0  29.3  0.349  42  1
723   5  117.0   86.0  30.0  105.0  39.1  0.251  42  0
726   1  116.0   78.0  29.0  180.0  36.1  0.496  25  0
730   3  130.0   78.0  23.0   79.0  28.4  0.323  34  1
732   2  174.0   88.0  37.0  120.0  44.5  0.646  24  1
733   2  106.0   56.0  27.0  165.0  29.0  0.426  22  0
736   0  126.0   86.0  27.0  120.0  27.4  0.515  21  0
738   2   99.0   60.0  17.0  160.0  36.6  0.453  21  0
740  11  120.0   80.0  37.0  150.0  42.3  0.785  48  1
741   3  102.0   44.0  20.0   94.0  30.8  0.400  26  0
742   1  109.0   58.0  18.0  116.0  28.5  0.219  22  0
744  13  153.0   88.0  37.0  140.0  40.6  1.174  39  0
745  12  100.0   84.0  33.0  105.0  30.0  0.488  46  0
747   1   81.0   74.0  41.0   57.0  46.3  1.096  32  0
748   3  187.0   70.0  22.0  200.0  36.4  0.408  36  1
751   1  121.0   78.0  39.0   74.0  39.0  0.261  28  0
753   0  181.0   88.0  44.0  510.0  43.3  0.222  26  1
755   1  128.0   88.0  39.0  110.0  36.5  1.057  37  1
760   2   88.0   58.0  26.0   16.0  28.4  0.766  22  0
763  10  101.0   76.0  48.0  180.0  32.9  0.171  63  0
765   5  121.0   72.0  23.0  112.0  26.2  0.245  30  0

[392 rows x 9 columns]

In [16]:
#printing the dimensions of the dataset
print(dataset.shape)

(392, 9)

In [18]:
#replacing missing values rows
dataset.fillna(dataset.mean(), inplace=True)
print(dataset.isnull().sum())
print(dataset.head(20))

dataset

0    0
1    0
2    0
3    0
4    0
5    0
6    0
7    0
8    0
dtype: int64
     0      1      2     3      4     5      6   7  8
3    1   89.0   66.0  23.0   94.0  28.1  0.167  21  0
4    0  137.0   40.0  35.0  168.0  43.1  2.288  33  1
6    3   78.0   50.0  32.0   88.0  31.0  0.248  26  1
8    2  197.0   70.0  45.0  543.0  30.5  0.158  53  1
13   1  189.0   60.0  23.0  846.0  30.1  0.398  59  1
14   5  166.0   72.0  19.0  175.0  25.8  0.587  51  1
16   0  118.0   84.0  47.0  230.0  45.8  0.551  31  1
18   1  103.0   30.0  38.0   83.0  43.3  0.183  33  0
19   1  115.0   70.0  30.0   96.0  34.6  0.529  32  1
20   3  126.0   88.0  41.0  235.0  39.3  0.704  27  0
24  11  143.0   94.0  33.0  146.0  36.6  0.254  51  1
25  10  125.0   70.0  26.0  115.0  31.1  0.205  41  1
27   1   97.0   66.0  15.0  140.0  23.2  0.487  22  0
28  13  145.0   82.0  19.0  110.0  22.2  0.245  57  0
31   3  158.0   76.0  36.0  245.0  31.6  0.851  28  1
32   3   88.0   58.0  11.0   54.0  24.8  0.267  22  0
35   4  103.0   60.0  33.0  192.0  24.0  0.966  33  0
39   4  111.0   72.0  47.0  207.0  37.1  1.390  56  1
40   3  180.0   64.0  25.0   70.0  34.0  0.271  26  0
43   9  171.0  110.0  24.0  240.0  45.4  0.721  54  1

      0      1      2     3      4     5      6   7  8
3     1   89.0   66.0  23.0   94.0  28.1  0.167  21  0
4     0  137.0   40.0  35.0  168.0  43.1  2.288  33  1
6     3   78.0   50.0  32.0   88.0  31.0  0.248  26  1
8     2  197.0   70.0  45.0  543.0  30.5  0.158  53  1
13    1  189.0   60.0  23.0  846.0  30.1  0.398  59  1
14    5  166.0   72.0  19.0  175.0  25.8  0.587  51  1
16    0  118.0   84.0  47.0  230.0  45.8  0.551  31  1
18    1  103.0   30.0  38.0   83.0  43.3  0.183  33  0
19    1  115.0   70.0  30.0   96.0  34.6  0.529  32  1
20    3  126.0   88.0  41.0  235.0  39.3  0.704  27  0
24   11  143.0   94.0  33.0  146.0  36.6  0.254  51  1
25   10  125.0   70.0  26.0  115.0  31.1  0.205  41  1
27    1   97.0   66.0  15.0  140.0  23.2  0.487  22  0
28   13  145.0   82.0  19.0  110.0  22.2  0.245  57  0
31    3  158.0   76.0  36.0  245.0  31.6  0.851  28  1
32    3   88.0   58.0  11.0   54.0  24.8  0.267  22  0
35    4  103.0   60.0  33.0  192.0  24.0  0.966  33  0
39    4  111.0   72.0  47.0  207.0  37.1  1.390  56  1
40    3  180.0   64.0  25.0   70.0  34.0  0.271  26  0
43    9  171.0  110.0  24.0  240.0  45.4  0.721  54  1
50    1  103.0   80.0  11.0   82.0  19.4  0.491  22  0
51    1  101.0   50.0  15.0   36.0  24.2  0.526  26  0
52    5   88.0   66.0  21.0   23.0  24.4  0.342  30  0
53    8  176.0   90.0  34.0  300.0  33.7  0.467  58  1
54    7  150.0   66.0  42.0  342.0  34.7  0.718  42  0
56    7  187.0   68.0  39.0  304.0  37.7  0.254  41  1
57    0  100.0   88.0  60.0  110.0  46.8  0.962  31  0
59    0  105.0   64.0  41.0  142.0  41.5  0.173  22  0
63    2  141.0   58.0  34.0  128.0  25.4  0.699  24  0
68    1   95.0   66.0  13.0   38.0  19.6  0.334  25  0
..   ..    ...    ...   ...    ...   ...    ...  .. ..
707   2  127.0   46.0  21.0  335.0  34.4  0.176  22  0
709   2   93.0   64.0  32.0  160.0  38.0  0.674  23  1
710   3  158.0   64.0  13.0  387.0  31.2  0.295  24  0
711   5  126.0   78.0  27.0   22.0  29.6  0.439  40  0
713   0  134.0   58.0  20.0  291.0  26.4  0.352  21  0
715   7  187.0   50.0  33.0  392.0  33.9  0.826  34  1
716   3  173.0   78.0  39.0  185.0  33.8  0.970  31  1
718   1  108.0   60.0  46.0  178.0  35.5  0.415  24  0
721   1  114.0   66.0  36.0  200.0  38.1  0.289  21  0
722   1  149.0   68.0  29.0  127.0  29.3  0.349  42  1
723   5  117.0   86.0  30.0  105.0  39.1  0.251  42  0
726   1  116.0   78.0  29.0  180.0  36.1  0.496  25  0
730   3  130.0   78.0  23.0   79.0  28.4  0.323  34  1
732   2  174.0   88.0  37.0  120.0  44.5  0.646  24  1
733   2  106.0   56.0  27.0  165.0  29.0  0.426  22  0
736   0  126.0   86.0  27.0  120.0  27.4  0.515  21  0
738   2   99.0   60.0  17.0  160.0  36.6  0.453  21  0
740  11  120.0   80.0  37.0  150.0  42.3  0.785  48  1
741   3  102.0   44.0  20.0   94.0  30.8  0.400  26  0
742   1  109.0   58.0  18.0  116.0  28.5  0.219  22  0
744  13  153.0   88.0  37.0  140.0  40.6  1.174  39  0
745  12  100.0   84.0  33.0  105.0  30.0  0.488  46  0
747   1   81.0   74.0  41.0   57.0  46.3  1.096  32  0
748   3  187.0   70.0  22.0  200.0  36.4  0.408  36  1
751   1  121.0   78.0  39.0   74.0  39.0  0.261  28  0
753   0  181.0   88.0  44.0  510.0  43.3  0.222  26  1
755   1  128.0   88.0  39.0  110.0  36.5  1.057  37  1
760   2   88.0   58.0  26.0   16.0  28.4  0.766  22  0
763  10  101.0   76.0  48.0  180.0  32.9  0.171  63  0
765   5  121.0   72.0  23.0  112.0  26.2  0.245  30  0

[392 rows x 9 columns]

In [20]:
#Sampling in pandas
df = pd.DataFrame({'num_legs': [2, 4, 8, 0],'num_wings': [2, 0, 0, 0],
                   'num_specimen_seen': [10, 2, 1, 8]},index=['falcon', 'dog', 'spider', 'fish'])
print(df)

print()
df['num_legs'].sample(n=3, random_state=None)#You can give it a specific state also by assigning numbers to it

        num_legs  num_wings  num_specimen_seen
falcon         2          2                 10
dog            4          0                  2
spider         8          0                  1
fish           0          0                  8

spider    8
falcon    2
dog       4
Name: num_legs, dtype: int64

In [24]:
#sampling in pandas
df.sample(frac=0.5, replace=True, random_state=None)

        num_legs  num_wings  num_specimen_seen
falcon         2          2                 10
fish           0          0                  8

In [22]:
#Normalisation of columns of a dataframe
normalized_df=(df-df.mean())/df.std()
normalized_df

        num_legs  num_wings  num_specimen_seen
falcon -0.439155        1.5           1.073372
dog     0.146385       -0.5          -0.734412
spider  1.317465       -0.5          -0.960386
fish   -1.024695       -0.5           0.621426

In [23]:
#Min-Max normalisation
normalized_df=(df-df.min())/(df.max()-df.min())
normalized_df

        num_legs  num_wings  num_specimen_seen
falcon      0.25        1.0           1.000000
dog         0.50        0.0           0.111111
spider      1.00        0.0           0.000000
fish        0.00        0.0           0.777778

In [26]:
#digitisation using bin's index
x = np.array([0.2, 1.4, 3.0, 1.6])
print(x)
bins = np.array([0.0, 1.0, 2.5, 4.0, 10.0])
print(bins)
inds = np.digitize(x, bins,right=False)
inds

[0.2 1.4 3.  1.6]
[ 0.   1.   2.5  4.  10. ]

array([1, 2, 3, 2], dtype=int64)

In [28]:
#Numpy's coeffiecient of correlation
x1=np.array([[3,25,4],[6,4,45],[34,2,3]])
print(np.corrcoef(x1, y=None, rowvar=True))
x1

[[ 1.         -0.50260944 -0.55747665]
 [-0.50260944  1.         -0.43751978]
 [-0.55747665 -0.43751978  1.        ]]

array([[ 3, 25,  4],
       [ 6,  4, 45],
       [34,  2,  3]])

In [30]:
#Now try corrcoef for this matrix and try to understand the result you are getting
import numpy as np
x2=np.ones((5,5))
x2[2][3]=2
x2[1][3]=5
print(x2)
np.corrcoef(x2, y=None, rowvar=True)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 5. 1.]
 [1. 1. 1. 2. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]

C:\Users\FDUSER.M-1734.002\Anaconda3\lib\site-packages\numpy\lib\function_base.py:2400: RuntimeWarning: invalid value encountered in true_divide
  c /= stddev[:, None]
C:\Users\FDUSER.M-1734.002\Anaconda3\lib\site-packages\numpy\lib\function_base.py:2401: RuntimeWarning: invalid value encountered in true_divide
  c /= stddev[None, :]

array([[nan, nan, nan, nan, nan],
       [nan,  1.,  1., nan, nan],
       [nan,  1.,  1., nan, nan],
       [nan, nan, nan, nan, nan],
       [nan, nan, nan, nan, nan]])

In [31]:
np.cov(x1, y=None, rowvar=True, bias=False, ddof=None, fweights=None, aweights=None)

array([[ 154.33333333, -144.33333333, -126.        ],
       [-144.33333333,  534.33333333, -184.        ],
       [-126.        , -184.        ,  331.        ]])